name:                visualiser
version:             0.1.0.0
github:              "githubuser/visualiser"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/visualiser#readme>

dependencies:
- base >= 4.7 && < 5
- brick == 0.62
- vty == 5.33
- text == 1.2.4.1
- microlens == 0.4.12.0
- time == 1.9.3
- vector == 0.12.3.1

library:
  source-dirs: src
  dependencies:
  - brick == 0.62

executables:
  visualiser-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - visualiser

tests:
  visualiser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - visualiser
